!!com.pcalouche.awtf_core.util.appConfig.AppConfig
appWebElements:
- {
  description: Global Search,
  locator: '#globalSearch',
  locatorType: css
}
- {
  description: Account History Dropdown,
  locator: '#accountHistoryDropdown',
  locatorType: css
}
- {
  description: Animal Dropdown,
  locator: '#animalDropdown',
  locatorType: css
}
- {
  description: Error Box,
  locator: .error-box,
  locatorType: css
}
- {
  description: Test Span App Element,
  locator: '#testSpanAppElement',
  locatorType: css
}
- {
  description: Web Design Menu Item,
  locator: Web Design,
  locatorType: linkText
}
- !!com.pcalouche.awtf_core.util.appConfig.Modal {
  description: Test,
  locator: '#testModal',
  locatorType: css
}
- !!com.pcalouche.awtf_core.util.appConfig.ElementWithTooltip
  description: Info Icon
  locator: .info-icon
  locatorType: css
  tooltipElement: {
    description: null,
    locator: '#infoIconTooltip',
    locatorType: css
  }
- !!com.pcalouche.awtf_core.util.appConfig.ElementWithTooltip
  description: Help Icon
  locator: .help-icon
  locatorType: css
  tooltipElement: {
    description: null,
    locator: '#helpIconTooltip',
    locatorType: css
  }
errorMessageClasses: [
  error,
  invalid]
loadingIndicatorLocator: {
  description: Loading Locator,
  locator: '.load-mask-large, .load-mask-medium, .load-mask-small',
  locatorType: css
}
messageBundleLocation: messages_en
modalLocator: {
  description: Modal Locator,
  locator: '//*[contains(@class,''modal'')]',
  locatorType: xpath
}
rowActionDefinitions:
- {
  description: select,
  locator: './/input[@type=''checkbox'' or @type=''radio'']',
  locatorType: xpath,
  rowAction: SELECT
}
- {
  description: deselect,
  locator: './/input[@type=''checkbox'' or @type=''radio'']',
  locatorType: xpath,
  rowAction: DESELECT
}
- {
  description: click,
  locator: .//a,
  locatorType: xpath,
  rowAction: CLICK
}
- {
  description: expand,
  locator: './/*[contains(@class,''row-expander collapsed'')]',
  locatorType: xpath,
  rowAction: EXPAND
}
- {
  description: collapse,
  locator: './/*[contains(@class,''row-expander expanded'')]',
  locatorType: xpath,
  rowAction: COLLAPSE
}
- {
  description: can select,
  locator: './/input[@type=''checkbox'' or @type=''radio'']',
  locatorType: xpath,
  rowAction: CAN_SELECT
}
- {
  description: cannot select,
  locator: './/input[@type=''checkbox'' or @type=''radio'']',
  locatorType: xpath,
  rowAction: CANNOT_SELECT
}
- {
  description: see,
  locator: '',
  locatorType: xpath,
  rowAction: SEE
}
- {
  description: do not see,
  locator: '',
  locatorType: xpath,
  rowAction: DO_NOT_SEE
}
- {
  description: see selected,
  locator: './/input[@type=''checkbox'' or @type=''radio'']',
  locatorType: xpath,
  rowAction: SEE_SELECTED
}
- {
  description: see deselected,
  locator: './/input[@type=''checkbox'' or @type=''radio'']',
  locatorType: xpath,
  rowAction: SEE_DESELECTED
}
tooltipLocator: {
  description: Tooltip Locator,
  locator: './/*[contains(@class, ''tooltip'')]',
  locatorType: xpath
}
